//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtraEscolares
    {
        public int idExtraescolar { get; set; }
        public int idActividad { get; set; }
        public int idInstructor { get; set; }
        public string horalunes { get; set; }
        public string horamartes { get; set; }
        public string horamiercoles { get; set; }
        public string hormajueves { get; set; }
        public string horaviernes { get; set; }
        public int idPeriodo { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
